# Generated by Django 3.2.3 on 2021-05-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
